import type { World } from "../types";

export const capDetector: World = {
  id: "cap",
  title: "Cap Detector",
  tagline: "Catch AI when it makes things up.",
  accent: "#e0a100",
  guide: { pose: "hips", face: "smug", wear: ["hero", "glasses"] },
  from: "Hallucination Hunter",
  status: "live",
  units: [
    {
      id: "cap-or-facts",
      title: "Cap or facts?",
      blurb: "The AI said it. Is it true?",
      cards: [
        {
          id: "cd-001",
          type: "cap",
          source: "ChatBot said",
          claim: "Water boils at a lower temperature on top of a high mountain than at sea level.",
          isCap: false,
          why: "Facts. Lower air pressure up high means water boils below 100°C. Real science, real answer.",
        },
        {
          id: "cd-002",
          type: "cap",
          source: "ChatBot said",
          claim: "The Great Wall of China is easy to see from the Moon with the naked eye.",
          isCap: true,
          why: "Cap. A very popular myth. The wall is long but far too narrow to see from the Moon.",
          meme: { kind: "drake", no: "it said so confidently", yes: "it said so AND a source backs it up" },
        },
        {
          id: "cd-003",
          type: "cap",
          source: "ChatBot said",
          claim: "Octopuses have three hearts.",
          isCap: false,
          why: "Facts. Two pump blood to the gills, one to the rest of the body. Wild but true.",
        },
        {
          id: "cd-004",
          type: "cap",
          source: "ChatBot said",
          claim: "Goldfish only have a 3-second memory.",
          isCap: true,
          why: "Cap. Studies show goldfish can remember things for months. The 3-second thing is a myth the internet loves.",
        },
        {
          id: "cd-005",
          type: "cap",
          source: "ChatBot said",
          claim: "Bananas are berries, but strawberries are not, botanically speaking.",
          isCap: false,
          why: "Facts. Botany is weird. Sounds fake, is real, which is exactly why you check.",
        },
        {
          id: "cd-006",
          type: "cap",
          source: "ChatBot said",
          claim: "Lightning never strikes the same place twice.",
          isCap: true,
          why: "Cap. Tall buildings get hit many times a year. A saying is not a fact.",
        },
      ],
    },
    {
      id: "spot-it",
      title: "Spot the fake",
      blurb: "One sentence was made up. Find it.",
      cards: [
        {
          id: "cd-101",
          type: "spot",
          prompt: "The AI wrote a short bio. Which line is made up?",
          sentences: [
            "Albert Einstein was born in Germany in 1879.",
            "He developed the theory of relativity.",
            "He won the Nobel Prize in Physics in 1921.",
            "He was also the first person to walk on the Moon.",
          ],
          answer: 3,
          why: "Real facts next to one wild one. Hallucinations hide between true sentences, so read every line.",
        },
        {
          id: "cd-102",
          type: "spot",
          prompt: "Homework help from the AI. Which line is wrong?",
          sentences: [
            "Plants make food using sunlight, water and carbon dioxide.",
            "This process is called photosynthesis.",
            "It mostly happens in the leaves.",
            "Plants breathe in oxygen to make their food.",
          ],
          answer: 3,
          why: "Photosynthesis takes in carbon dioxide and gives off oxygen. The AI flipped it, and it sounds just as confident.",
        },
        {
          id: "cd-103",
          type: "spot",
          prompt: "The AI recommended sources for your essay. Which is the red flag?",
          sentences: [
            "A link to your country's official statistics website.",
            "A textbook your teacher assigned.",
            "\"Smith, J. (2019). The Complete Truth About Everything. Journal of Real Facts, 12(4).\"",
            "An encyclopedia article you can open and read.",
          ],
          answer: 2,
          why: "AI often invents citations that look perfect. If you can't find the paper, it doesn't exist.",
          meme: { kind: "expect", expectation: "AI gives me 5 real sources", reality: "3 of them never existed" },
        },
        {
          id: "cd-104",
          type: "spot",
          prompt: "Travel tips from the AI. Which one is cap?",
          sentences: [
            "Toronto is in the province of Ontario.",
            "The CN Tower is in downtown Toronto.",
            "Toronto is the capital city of Canada.",
            "Lake Ontario is next to the city.",
          ],
          answer: 2,
          why: "Ottawa is Canada's capital. Toronto is Ontario's. A classic mix-up the AI repeats.",
        },
      ],
    },
    {
      id: "verify",
      title: "Verify like a pro",
      blurb: "What to do when you're not sure.",
      cards: [
        {
          id: "cd-201",
          type: "order",
          prompt: "You got an AI answer for a school project. Put the checks in order:",
          steps: ["Read the whole answer", "Pick the claims that matter", "Look them up in a trusted source", "Fix or cut anything you can't confirm"],
          why: "Read, pick, check, fix. Two minutes of checking saves a bad grade.",
        },
        {
          id: "cd-202",
          type: "choice",
          prompt: "Which is the most reliable way to check a fact the AI gave you?",
          options: ["Ask the same AI again", "Find it on an official or well-known source", "Check if it sounds smart"],
          answer: 1,
          why: "A second opinion has to come from outside the AI. Asking again just gets another guess.",
        },
        {
          id: "cd-203",
          type: "choice",
          prompt: "When should you double-check an AI answer the MOST?",
          options: ["Medical, money or legal stuff", "A joke", "A name for your cat"],
          answer: 0,
          why: "Higher stakes, more checking. A wrong cat name is funny; a wrong medicine dose is not.",
          meme: { kind: "fine", caption: "trusting AI on medicine doses without checking" },
        },
        {
          id: "cd-204",
          type: "cap",
          claim: "If an AI gives a link, the link must lead to a real page.",
          isCap: true,
          why: "Cap. AI can generate links that look real and go nowhere. Click before you cite.",
        },
        {
          id: "cd-205",
          type: "type",
          prompt: "Checking a claim against a trusted source is called fact-________.",
          accept: ["checking", "check"],
          why: "Fact-checking: the habit that makes you smarter than the bot.",
        },
      ],
    },
  ],
};
