import type { World } from "../types";

// Ported from Circuit Prophet (legacy suite) on 2026-10-03: easy and medium items, answers placed by a stable hash.
export const circuitLab: World = {
  id: "circuit",
  title: "Circuit Lab",
  tagline: "How computers work, down to the wires.",
  accent: "#ff8a00",
  guide: { pose: "type", face: "happy", wear: ["hero"] },
  from: "Circuit Prophet",
  status: "live",
  units: [
    { id: "parts", title: "The parts bin", blurb: "What's actually on a circuit board.", cards: [
        { id: "comp-001", type: "choice", prompt: "What is the primary function of a resistor?", options: ["To store electrical energy", "To amplify signals", "To limit current flow in a circuit", "To convert AC to DC"], answer: 2, why: "Resistors are the most common electronic component. They protect other components from excess current." },
        { id: "comp-002", type: "choice", prompt: "A resistor has bands: Brown, Black, Red, Gold. What is its resistance?", options: ["100Ω", "1000Ω or 1kΩ (10 × 10² = 1000, Gold = ±5%)", "10,000Ω", "10Ω"], answer: 1, why: "Reading color codes is a fundamental skill. You'll encounter it in every lab and repair job." },
        { id: "comp-003", type: "choice", prompt: "What does a capacitor store?", options: ["Electrical resistance", "Magnetic energy", "Electrical charge (energy in an electric field)", "Kinetic energy"], answer: 2, why: "Capacitors smooth power supplies, filter signals, and store energy for quick release. Camera flashes use large capacitors to store energy and release it instantly as a bright flash." },
        { id: "comp-004", type: "choice", prompt: "What does an inductor store energy in?", options: ["An electric field", "Chemical bonds", "A magnetic field", "Thermal energy"], answer: 2, why: "Inductors resist changes in current, making them essential for power supplies and filters. The coils in a wireless phone charger are inductors that transfer energy through magnetic fields." },
        { id: "comp-005", type: "choice", prompt: "What is the unit of capacitance?", options: ["Henry (H)", "Farad (F)", "Ohm (Ω)", "Coulomb (C)"], answer: 1, why: "Units are the language of engineering. Confusing farads and henrys is like confusing meters and kilograms." },
        { id: "comp-006", type: "choice", prompt: "What does a diode do?", options: ["Amplifies current in both directions", "Allows current to flow in one direction only", "Stores energy temporarily", "Converts DC to AC"], answer: 1, why: "Diodes are essential for rectification (converting AC to DC) and protecting circuits from reverse polarity." },
        { id: "comp-007", type: "choice", prompt: "In an NPN transistor, current flows from collector to emitter when:", options: ["A small current is applied to the base", "Voltage is removed from the base", "The collector is grounded", "The emitter is at higher voltage than the collector"], answer: 0, why: "Transistors are the foundation of all modern electronics. They switch and amplify signals. A single modern CPU contains billions of transistors, each acting as a tiny on/off switch." },
    ] },
    { id: "gates", title: "Logic gates", blurb: "Computers think in yes and no.", cards: [
        { id: "lg-001", type: "choice", prompt: "AND gate: inputs are 1 and 1. What is the output?", options: ["0", "1", "Undefined", "Both 0 and 1"], answer: 1, why: "AND gates are used in enable logic: a circuit only activates when ALL conditions are met. A car starts only when the key is turned AND the brake is pressed AND the door is closed." },
        { id: "lg-002", type: "choice", prompt: "OR gate: inputs are 0 and 1. What is the output?", options: ["0", "Undefined", "1", "Depends on the gate"], answer: 2, why: "OR gates combine multiple trigger conditions. If any one is true, the output fires. A fire alarm triggers if smoke sensor OR heat sensor OR manual pull station activates." },
        { id: "lg-003", type: "choice", prompt: "NOT gate: input is 1. What is the output?", options: ["1", "Undefined", "0", "-1"], answer: 2, why: "NOT gates (inverters) create complementary signals needed for flip-flops and memory cells. A normally-open switch: when you're NOT pressing it, the circuit is open (0). Press = 1, NOT pressed = 0." },
        { id: "lg-004", type: "choice", prompt: "AND gate: inputs are 1 and 0. What is the output?", options: ["0", "1", "Undefined", "Error"], answer: 0, why: "AND gates act as gatekeepers. If even one input is 0, the output is 0. Two-factor authentication: you need password AND phone verification (both = 1) to access your account." },
        { id: "lg-005", type: "choice", prompt: "OR gate: inputs are 0 and 0. What is the output?", options: ["1", "0", "Undefined", "Error"], answer: 1, why: "OR only outputs 0 when ALL inputs are 0. This is the only case where OR produces 0. No fire detected by any sensor = no alarm. All inputs must be 0 for OR to output 0." },
        { id: "lg-006", type: "choice", prompt: "NAND gate: inputs are 1 and 1. What is the output?", options: ["0", "1", "Undefined", "Error"], answer: 0, why: "NAND is a universal gate: you can build ANY other gate using only NAND gates. Early computers were built entirely from NAND gates because they're cheapest to manufacture." },
        { id: "lg-007", type: "choice", prompt: "NOR gate: inputs are 0 and 0. What is the output?", options: ["0", "Undefined", "1", "Error"], answer: 2, why: "NOR is also a universal gate. The Apollo Guidance Computer was built entirely from NOR gates." },
    ] },
    { id: "binary", title: "Ones and zeros", blurb: "How a computer counts.", cards: [
        { id: "ds-002", type: "choice", prompt: "Convert decimal 15 to binary.", options: ["1110", "10001", "1111 (8+4+2+1 = 15)", "1100"], answer: 2, why: "Converting between number systems is a fundamental skill for any programmer or hardware engineer." },
        { id: "ds-005", type: "choice", prompt: "Convert binary 11001100 to hexadecimal.", options: ["0xAA", "0xDD", "0xBB", "0xCC (1100=C, 1100=C)"], answer: 3, why: "Split binary into 4-bit groups from the right, convert each to hex. Fast and mechanical. Memory addresses in debuggers are always shown in hex because it maps perfectly to binary." },
        { id: "ds-006", type: "choice", prompt: "What is 0101 + 0011 in binary?", options: ["0111", "1000 (5 + 3 = 8 in decimal)", "1001", "0110"], answer: 1, why: "Binary addition is what the ALU actually does. Every calculation reduces to this. When your CPU adds two numbers, the ALU performs binary addition using full adder circuits." },
        { id: "ds-008", type: "choice", prompt: "In the memory hierarchy, which is fastest?", options: ["L1 Cache", "RAM", "CPU Registers", "SSD"], answer: 2, why: "The memory hierarchy trades speed for capacity. Registers are tiny but access in one clock cycle." },
        { id: "ds-009", type: "choice", prompt: "What does 'clock speed' measure in a CPU?", options: ["The physical speed of electron flow", "The number of cores in the processor", "The amount of data transferred per second", "The number of cycles the CPU executes per second"], answer: 3, why: "Clock speed (GHz) sets the heartbeat of the processor. Higher isn't always faster due to IPC differences." },
        { id: "ds-010", type: "choice", prompt: "How many bits are in a standard memory address on a 64-bit system?", options: ["64 bits", "32 bits", "128 bits", "16 bits"], answer: 0, why: "64-bit addresses allow theoretically 16 exabytes of addressable memory, far beyond current needs." },
    ] },
    { id: "cpu", title: "Inside the CPU", blurb: "The brain of the machine.", cards: [
        { id: "cpu-001", type: "choice", prompt: "What does the ALU (Arithmetic Logic Unit) do?", options: ["Stores data permanently", "Controls the flow of instructions", "Manages input and output devices", "Performs mathematical and logical operations"], answer: 3, why: "The ALU is the computational core. Every add, subtract, AND, OR, and compare happens here. When you type 2+2 in a calculator app, the ALU is what actually computes the answer." },
        { id: "cpu-002", type: "choice", prompt: "What is the purpose of CPU registers?", options: ["To store the operating system", "To hold data and instructions currently being processed", "To cool the processor", "To connect the CPU to RAM"], answer: 1, why: "Registers are the fastest storage in a computer. The ALU can only operate on data in registers." },
        { id: "cpu-003", type: "choice", prompt: "What are the three stages of the basic CPU cycle?", options: ["Read, Write, Delete", "Input, Process, Output", "Load, Store, Jump", "Fetch, Decode, Execute"], answer: 3, why: "The fetch-decode-execute cycle is the fundamental operation loop of every CPU ever made. A modern CPU executes billions of fetch-decode-execute cycles per second." },
        { id: "cpu-004", type: "choice", prompt: "What is L1 cache?", options: ["The smallest, fastest cache memory built directly into the CPU core", "A type of RAM module", "External storage on the motherboard", "A software-level caching mechanism"], answer: 0, why: "L1 cache has 1-2 cycle latency. It's tiny (32-64KB) but accessed constantly. Apple's M-series chips have 192KB L1 instruction cache per performance core: larger than most competitors." },
        { id: "cpu-005", type: "choice", prompt: "What does the Control Unit do in a CPU?", options: ["Performs arithmetic calculations", "Stores program data", "Manages the power supply", "Directs the operation of the processor by interpreting instructions"], answer: 3, why: "The Control Unit is the conductor of the orchestra. It tells every other component when and what to do." },
        { id: "cpu-009", type: "choice", prompt: "How many levels of cache does a typical modern CPU have?", options: ["1 level", "3 levels (L1, L2, L3)", "2 levels", "5 levels"], answer: 1, why: "Each cache level trades speed for capacity. L1 is tiny/fast, L3 is large/slower. Apple M4: 192KB L1, 16MB L2, 36MB L3 (shared). AMD Ryzen 9: 64KB L1, 1MB L2, 64MB L3." },
        { id: "cpu-010", type: "choice", prompt: "What is the program counter (PC)?", options: ["A counter that tracks how many programs are running", "A register that holds the memory address of the next instruction to execute", "A device that counts clock cycles", "A register that stores the result of the last operation"], answer: 1, why: "The PC is how the CPU knows what to do next. Jumps and branches work by modifying the PC. When you call a function, the PC is saved on the stack and updated to the function's address." },
    ] },
  ],
};
