import type { World } from "../types";

// Ported from NetRunner (legacy suite) on 2026-10-03: easy and medium items, answers placed by a stable hash.
export const netRun: World = {
  id: "net",
  title: "Net Run",
  tagline: "How the internet moves your stuff.",
  accent: "#00a6c8",
  guide: { pose: "run", face: "grin", wear: ["hero"] },
  from: "NetRunner",
  status: "live",
  units: [
    { id: "layers", title: "How data travels", blurb: "Seven layers, one cat video.", cards: [
        { id: "osi-001", type: "choice", prompt: "Which OSI layer is responsible for converting data into electrical, optical, or radio signals?", options: ["Layer 2: Data Link", "Layer 3: Network", "Layer 1: Physical", "Layer 7: Application"], answer: 2, why: "Without the Physical layer, there's no way to actually move bits across a wire, fiber, or airwave." },
        { id: "osi-002", type: "choice", prompt: "Which OSI layer uses MAC addresses to forward frames between devices on the same network?", options: ["Layer 1: Physical", "Layer 2: Data Link", "Layer 3: Network", "Layer 4: Transport"], answer: 1, why: "MAC addresses are the foundation of local network communication: every NIC has a unique one burned in." },
        { id: "osi-003", type: "choice", prompt: "Which OSI layer handles logical addressing and routing between different networks?", options: ["Layer 2: Data Link", "Layer 3: Network", "Layer 4: Transport", "Layer 5: Session"], answer: 1, why: "IP addresses live here: without Layer 3, packets couldn't find their way across the internet." },
        { id: "osi-004", type: "choice", prompt: "Which OSI layer ensures reliable end-to-end data delivery using segments?", options: ["Layer 3: Network", "Layer 5: Session", "Layer 6: Presentation", "Layer 4: Transport"], answer: 3, why: "TCP and UDP both live here: they determine whether your data arrives reliably or just fast." },
        { id: "osi-005", type: "choice", prompt: "Which OSI layer manages sessions (establishment, maintenance, teardown) between applications?", options: ["Layer 4: Transport", "Layer 5: Session", "Layer 6: Presentation", "Layer 7: Application"], answer: 1, why: "Sessions keep track of who's talking to whom: critical for maintaining state in conversations." },
        { id: "osi-006", type: "choice", prompt: "Which OSI layer handles data encryption, compression, and format translation?", options: ["Layer 5: Session", "Layer 6: Presentation", "Layer 7: Application", "Layer 4: Transport"], answer: 1, why: "This layer ensures data looks the same on both ends: think character encoding, encryption, image formats." },
        { id: "osi-007", type: "choice", prompt: "Which OSI layer is closest to the end user and provides network services to applications?", options: ["Layer 6: Presentation", "Layer 7: Application", "Layer 5: Session", "Layer 4: Transport"], answer: 1, why: "This is where users interact with the network: HTTP, FTP, SMTP, DNS all live here. When you type a URL in your browser, HTTP at Layer 7 initiates the request." },
    ] },
    { id: "addresses", title: "Addresses", blurb: "Every device has a home address.", cards: [
        { id: "ip-001", type: "choice", prompt: "How many bits are in an IPv4 address?", options: ["32 bits", "64 bits", "128 bits", "16 bits"], answer: 0, why: "32 bits gives us ~4.3 billion addresses: which seemed infinite in the 1980s but ran out by 2011." },
        { id: "ip-002", type: "choice", prompt: "Which IPv4 address range is reserved for Class A private networks?", options: ["172.16.0.0: 172.31.255.255", "192.168.0.0: 192.168.255.255", "10.0.0.0: 10.255.255.255", "169.254.0.0: 169.254.255.255"], answer: 2, why: "Private addresses are not routable on the internet: they're used internally and need NAT to reach the web." },
        { id: "ip-003", type: "choice", prompt: "What is the loopback address used to test the local TCP/IP stack?", options: ["127.0.0.1", "0.0.0.0", "192.168.0.1", "255.255.255.255"], answer: 0, why: "Pinging 127.0.0.1 confirms your network stack works: no cable or NIC needed. Developers use localhost (127.0.0.1) to test web servers running on their own machine." },
        { id: "ip-004", type: "choice", prompt: "Which address class has a default subnet mask of 255.255.0.0?", options: ["Class B", "Class A", "Class C", "Class D"], answer: 0, why: "Class B networks support ~65,000 hosts: medium-sized organizations use this range. The 172.16.0.0/16 private range is Class B, commonly used in corporate networks." },
        { id: "ip-005", type: "choice", prompt: "What does a 169.254.x.x address indicate?", options: ["APIPA: the device failed to get an address from DHCP", "A multicast group address", "A private Class A address", "A DNS resolution failure"], answer: 0, why: "Seeing 169.254.x.x means DHCP is broken: the device auto-assigned a link-local address as a fallback." },
        { id: "ip-006", type: "choice", prompt: "In the IP address 192.168.1.100/24, what is the network portion?", options: ["192.168.0.0", "192.168.1.0", "192.168.1.100", "192.0.0.0"], answer: 1, why: "The network portion identifies which network a host belongs to: routers use this to make forwarding decisions." },
        { id: "ip-007", type: "choice", prompt: "What is the broadcast address for the network 192.168.1.0/24?", options: ["192.168.1.0", "192.168.1.1", "192.168.255.255", "192.168.1.255"], answer: 3, why: "The broadcast address sends a packet to every host on the subnet: it's the last address in the range." },
    ] },
    { id: "phonebook", title: "The internet's phonebook", blurb: "Names to numbers, automatically.", cards: [
        { id: "dns-001", type: "choice", prompt: "What type of DNS record maps a domain name to an IPv4 address?", options: ["AAAA record", "CNAME record", "A record", "MX record"], answer: 2, why: "A records are the most fundamental DNS record type: they tell the internet where your server is." },
        { id: "dns-002", type: "choice", prompt: "What type of DNS record maps a domain name to an IPv6 address?", options: ["AAAA record", "A record", "NS record", "PTR record"], answer: 0, why: "As IPv6 adoption grows, AAAA records become increasingly important for reachability. google.com has both A (142.250.80.46) and AAAA (2607:f8b0:4004:800::200e) records." },
        { id: "dns-003", type: "choice", prompt: "Which DNS record type creates an alias pointing one domain to another?", options: ["A record", "MX record", "SOA record", "CNAME record"], answer: 3, why: "CNAMEs let you point multiple names to the same destination: simplifying management when IPs change." },
        { id: "dns-004", type: "choice", prompt: "Which DNS record directs email to the correct mail server?", options: ["MX record", "A record", "CNAME record", "TXT record"], answer: 0, why: "Without MX records, sending email to your domain would fail: mail servers don't know where to deliver." },
        { id: "dns-005", type: "choice", prompt: "What does a PTR record do?", options: ["Points a domain to a mail server", "Creates an alias for another domain", "Specifies the authoritative name server", "Maps an IP address back to a domain name (reverse DNS)"], answer: 3, why: "Reverse DNS is used by mail servers to verify sender legitimacy: no PTR often means email gets flagged as spam." },
        { id: "dns-006", type: "choice", prompt: "What is the first step in DNS resolution when you type a URL in your browser?", options: ["Check the local DNS cache", "Query the root DNS server", "Contact the ISP's DNS server", "Send a request to the authoritative server"], answer: 0, why: "Caching dramatically speeds up DNS: most lookups are resolved locally without hitting the network." },
        { id: "dns-007", type: "choice", prompt: "Which DNS record type identifies the authoritative name server for a domain?", options: ["SOA record", "A record", "SRV record", "NS record"], answer: 3, why: "NS records tell the DNS system which servers are authoritative for a domain: they drive the delegation chain." },
    ] },
    { id: "ports", title: "Doors and ports", blurb: "Which door does each app knock on?", cards: [
        { id: "port-001", type: "choice", prompt: "Which port does HTTP use by default?", options: ["443", "8080", "80", "22"], answer: 2, why: "Port 80 is the default for unencrypted web traffic: most websites have migrated to HTTPS (443)." },
        { id: "port-002", type: "choice", prompt: "Which port does HTTPS use by default?", options: ["80", "443", "8443", "993"], answer: 1, why: "Port 443 carries encrypted web traffic: all sensitive data (banking, email, shopping) should use it." },
        { id: "port-003", type: "choice", prompt: "Which port does SSH use by default?", options: ["23", "3389", "21", "22"], answer: 3, why: "SSH provides encrypted remote terminal access: it replaced insecure Telnet (port 23). System administrators SSH into Linux servers to manage them remotely: ssh user@server -p 22." },
        { id: "port-004", type: "choice", prompt: "Which port does DNS use by default?", options: ["53", "67", "80", "25"], answer: 0, why: "DNS on port 53 is one of the most critical services: without it, domain names don't resolve." },
        { id: "port-005", type: "choice", prompt: "Which port does SMTP (email sending) use by default?", options: ["25", "110", "143", "587"], answer: 0, why: "Port 25 is the standard SMTP port: but many ISPs block it to prevent spam from consumer connections." },
        { id: "port-006", type: "choice", prompt: "Which ports does DHCP use?", options: ["67 (server) and 68 (client)", "53 and 54", "80 and 443", "161 and 162"], answer: 0, why: "DHCP automatically assigns IP addresses: knowing its ports helps troubleshoot auto-configuration failures." },
        { id: "port-007", type: "choice", prompt: "Which port does POP3 (email retrieval) use by default?", options: ["143", "110", "993", "25"], answer: 1, why: "POP3 downloads email and typically deletes it from the server: understanding the port helps with email setup." },
    ] },
    { id: "fix-wifi", title: "Fix the Wi-Fi", blurb: "Be the friend who actually fixes it.", cards: [
        { id: "tshoot-001", type: "choice", prompt: "A user can ping 8.8.8.8 but cannot reach google.com. What is the most likely issue?", options: ["Default gateway misconfiguration", "DNS resolution failure", "Firewall blocking HTTP", "NIC driver failure"], answer: 1, why: "If IP connectivity works but names don't resolve, DNS is always the suspect. This is the #1 helpdesk question." },
        { id: "tshoot-002", type: "choice", prompt: "Which command tests connectivity to a remote host and measures round-trip time?", options: ["ping", "traceroute", "nslookup", "netstat"], answer: 0, why: "Ping is the first tool you reach for: it instantly tells you if a host is reachable and how fast." },
        { id: "tshoot-003", type: "choice", prompt: "Which command shows the path packets take to reach a destination, hop by hop?", options: ["ping", "netstat", "traceroute (tracert on Windows)", "nslookup"], answer: 2, why: "Traceroute reveals where packets are getting stuck or delayed: essential for diagnosing routing issues." },
        { id: "tshoot-004", type: "choice", prompt: "Which command queries DNS servers to resolve a domain name?", options: ["ipconfig", "netstat", "nslookup", "ping"], answer: 2, why: "nslookup lets you test DNS resolution and check which DNS server is responding: critical for DNS troubleshooting." },
        { id: "tshoot-005", type: "choice", prompt: "Which command displays active network connections and listening ports on the local machine?", options: ["traceroute", "netstat", "nslookup", "ipconfig"], answer: 1, why: "netstat shows what's connected to your machine and what's listening: essential for security and troubleshooting." },
        { id: "tshoot-006", type: "choice", prompt: "Which Windows command shows the IP configuration including IP address, subnet mask, and default gateway?", options: ["ifconfig", "ip addr", "ipconfig", "netstat"], answer: 2, why: "ipconfig is your first stop on Windows: it reveals the device's IP settings, which are often the root cause." },
        { id: "tshoot-007", type: "choice", prompt: "A user's PC has an IP address of 169.254.x.x. What should you check first?", options: ["DNS server configuration", "Firewall rules blocking web traffic", "The user's browser settings", "DHCP server connectivity: the PC failed to get an address from DHCP"], answer: 3, why: "169.254.x.x (APIPA) is the automatic fallback when DHCP fails: the user won't have internet access." },
    ] },
  ],
};
