import type { World } from "../types";

export const promptDojo: World = {
  id: "prompt",
  title: "Prompt Dojo",
  tagline: "Talk to AI so it actually helps.",
  accent: "#ff3b1f",
  guide: { pose: "point", face: "smug", wear: ["hero"] },
  from: "Prompt Craft",
  status: "live",
  units: [
    {
      id: "say-it",
      title: "Say what you mean",
      blurb: "Vague in, vague out.",
      cards: [
        {
          id: "pd-001",
          type: "choice",
          prompt: "Which prompt gets the better birthday message for your little sister?",
          options: ["Write a birthday message.", "Write a funny 2-line birthday text for my 12-year-old sister who loves cats and hates mornings."],
          answer: 1,
          why: "Details are the cheat code. Who it's for, how long, and what vibe.",
          meme: { kind: "drake", no: "write a birthday message", yes: "2 lines, 12 y/o sister, loves cats, hates mornings" },
        },
        {
          id: "pd-002",
          type: "choice",
          prompt: "You want a study plan. What's missing from: \"Make me a study plan\"?",
          options: ["Nothing, it's perfect", "The subject, the deadline and how much time you have", "The word please"],
          answer: 1,
          why: "AI can't read your mind. Subject, deadline and time turn a generic plan into YOUR plan.",
        },
        {
          id: "pd-003",
          type: "cap",
          claim: "Saying \"you are an expert chef\" at the start of a prompt can change the style of the answer.",
          isCap: false,
          why: "Giving the AI a role sets the voice and depth. It's a costume, not a superpower.",
        },
        {
          id: "pd-004",
          type: "choice",
          prompt: "You need the answer as a table. Best move?",
          options: ["Hope it guesses", "Say \"put it in a table with columns: name, price, rating\"", "Ask three times"],
          answer: 1,
          why: "Ask for the format you want, and name the columns. The AI follows shape requests well.",
        },
        {
          id: "pd-005",
          type: "type",
          prompt: "Showing the AI an example of what you want is called ___-shot prompting. (one word: how many examples? more than zero...)",
          accept: ["few", "few-shot", "one", "one-shot"],
          hint: "Not zero. A ___.",
          why: "Few-shot = give a couple of examples first. The AI copies the pattern.",
        },
        {
          id: "pd-006",
          type: "choice",
          prompt: "The answer came back too long. Fastest fix?",
          options: ["Start over in a new chat", "Reply: \"Shorter. 3 bullets max.\"", "Close the app"],
          answer: 1,
          why: "Prompting is a conversation. Steer it with a follow-up instead of restarting.",
          meme: { kind: "buttons", a: "start a new chat", b: "say \"shorter\"", caption: "the obvious one is right there" },
        },
      ],
    },
    {
      id: "recipe",
      title: "The recipe",
      blurb: "Every strong prompt has the same parts.",
      cards: [
        {
          id: "pd-101",
          type: "order",
          prompt: "Build the prompt in a sensible order:",
          steps: [
            "Context: I run a small sneaker shop in Toronto.",
            "Task: Write an Instagram caption for our new drop.",
            "Audience: teens and 20-somethings.",
            "Format: under 30 words, 2 emojis max.",
          ],
          why: "Context, task, audience, format. Set the scene, say the job, say who it's for, say the shape.",
        },
        {
          id: "pd-102",
          type: "choice",
          prompt: "Which part tells the AI WHO will read the answer?",
          options: ["Audience", "Tone", "Format", "Context"],
          answer: 0,
          why: "Audience changes everything. Explain gravity to a 7-year-old vs a physics student.",
        },
        {
          id: "pd-103",
          type: "choice",
          prompt: "\"Make it sound friendly but not cringe.\" That line sets the...",
          options: ["Task", "Tone", "Audience", "Length"],
          answer: 1,
          why: "Tone is the vibe. Friendly, serious, hype, calm. Say it out loud.",
        },
        {
          id: "pd-104",
          type: "cap",
          claim: "A longer prompt is always a better prompt.",
          isCap: true,
          why: "Cap. Clear beats long. Extra fluff can bury the part that matters.",
          meme: { kind: "expect", expectation: "500-word prompt = genius answer", reality: "AI focuses on the wrong paragraph" },
        },
        {
          id: "pd-105",
          type: "choice",
          prompt: "You want the AI to NOT do something. Best way to say it?",
          options: ["Don't mention it at all", "Say it clearly: \"Do not use slang.\"", "Use all caps and yell"],
          answer: 1,
          why: "Constraints work when they're stated plainly. Yelling isn't a feature.",
        },
        {
          id: "pd-106",
          type: "type",
          prompt: "A rule like \"under 50 words\" or \"no jargon\" is called a ________.",
          accept: ["constraint", "constraints", "rule", "limit"],
          hint: "starts with c, rhymes with complaint",
          why: "Constraints are guardrails. They keep the answer in the lane you want.",
        },
      ],
    },
    {
      id: "level-up",
      title: "Level up your prompts",
      blurb: "Tricks the pros use.",
      cards: [
        {
          id: "pd-201",
          type: "choice",
          prompt: "For a tricky math word problem, which line usually helps the AI get it right?",
          options: ["\"Answer fast.\"", "\"Think step by step before answering.\"", "\"You'd better be right.\""],
          answer: 1,
          why: "Asking for steps makes the AI show its working, which catches mistakes.",
          meme: { kind: "galaxy", levels: ["just ask", "ask clearly", "ask for steps", "ask for steps, then check them"] },
        },
        {
          id: "pd-202",
          type: "order",
          prompt: "Put the pro workflow in order:",
          steps: ["Write a first prompt", "Read the answer", "Say what's off", "Get a better answer", "Save the prompt that worked"],
          why: "Prompt, read, correct, repeat. Then keep the winner so you never write it twice.",
        },
        {
          id: "pd-203",
          type: "cap",
          claim: "If the AI sounds confident, the answer is correct.",
          isCap: true,
          why: "Cap. AI sounds confident even when it's wrong. Confidence is a tone, not proof.",
        },
        {
          id: "pd-204",
          type: "choice",
          prompt: "You paste a long article and ask for a summary. What makes it better?",
          options: ["Say who it's for and how long", "Paste it twice", "Add random keywords"],
          answer: 0,
          why: "\"Summarise for a busy manager in 5 bullets\" beats \"summarise\" every time.",
        },
        {
          id: "pd-205",
          type: "choice",
          prompt: "Which one is a privacy fail?",
          options: ["Asking for a recipe", "Pasting your password into a chatbot", "Asking for a workout plan"],
          answer: 1,
          why: "Never paste passwords, bank info or private stuff. Treat a chat box like a public room.",
          meme: { kind: "fine", caption: "pasting my password into the chatbot" },
        },
        {
          id: "pd-206",
          type: "type",
          prompt: "The text you type to an AI is called a ______.",
          accept: ["prompt"],
          why: "The prompt is your half of the deal. Better prompt, better result.",
        },
      ],
    },
  ],
};
