import type { World } from "../types";

export const tokenTemple: World = {
  id: "token",
  title: "Token Temple",
  tagline: "See how AI actually thinks: one word at a time.",
  accent: "#2f6bff",
  guide: { pose: "think", face: "zen", wear: ["hero"] },
  from: "Token Prophet",
  status: "live",
  units: [
    {
      id: "next-word",
      title: "The next-word machine",
      blurb: "Every chatbot is guessing the next piece of text.",
      cards: [
        {
          id: "tt-001",
          type: "predict",
          context: "Peanut butter and ___",
          options: [{ token: "jelly", p: 0.78 }, { token: "bread", p: 0.12 }, { token: "rice", p: 0.02 }],
          why: "A language model picks the next word by how often it followed text like this in what it learned from.",
          meme: { kind: "galaxy", levels: ["AI is magic", "AI is a search engine", "AI predicts the next word", "AI predicts the next TOKEN"] },
        },
        {
          id: "tt-002",
          type: "cap",
          claim: "A chatbot writes its whole answer at once, then shows it to you.",
          isCap: true,
          why: "Cap. It writes one token at a time, and each new token is chosen using everything before it. That's why answers stream in.",
        },
        {
          id: "tt-003",
          type: "predict",
          context: "The capital of France is ___",
          options: [{ token: "Paris", p: 0.94 }, { token: "a", p: 0.03 }, { token: "Lyon", p: 0.01 }],
          why: "Strong patterns give one clear winner. Facts that show up everywhere are easy guesses.",
        },
        {
          id: "tt-004",
          type: "choice",
          prompt: "What is a token?",
          options: ["A crypto coin", "A chunk of text: a word or a piece of a word", "A password"],
          answer: 1,
          why: "Models read and write in tokens. \"Unbelievable\" might be 3 tokens: un, believ, able.",
        },
        {
          id: "tt-005",
          type: "predict",
          context: "I'm so hungry I could eat a ___",
          options: [{ token: "horse", p: 0.71 }, { token: "lot", p: 0.15 }, { token: "salad", p: 0.01 }],
          why: "Idioms are super predictable. The model learned the phrase, not your actual hunger.",
        },
        {
          id: "tt-006",
          type: "type",
          prompt: "LLM stands for Large ________ Model.",
          accept: ["language"],
          why: "Large Language Model: trained on a huge amount of text to predict what comes next.",
        },
      ],
    },
    {
      id: "dials",
      title: "The dials",
      blurb: "Temperature, context and memory.",
      cards: [
        {
          id: "tt-101",
          type: "choice",
          prompt: "Turning the \"temperature\" UP makes the AI's answers...",
          options: ["More random and creative", "Hotter", "Shorter", "More accurate"],
          answer: 0,
          why: "Higher temperature lets less likely tokens win more often. Fun for poems, risky for facts.",
          meme: { kind: "buttons", a: "temperature 0: same answer every time", b: "temperature 1.5: chaos poet", caption: "pick your fighter" },
        },
        {
          id: "tt-102",
          type: "choice",
          prompt: "For a math answer you want to be consistent, you'd set temperature...",
          options: ["Low", "High", "It doesn't matter"],
          answer: 0,
          why: "Low temperature means the model sticks to its top guess. Good for facts and code.",
        },
        {
          id: "tt-103",
          type: "choice",
          prompt: "The \"context window\" is...",
          options: ["The chat app's window size", "How much text the model can look at at once", "The model's personality"],
          answer: 1,
          why: "Context window = the model's working memory for one conversation. Past it, early stuff falls out.",
        },
        {
          id: "tt-104",
          type: "cap",
          claim: "Chatbots remember everything you said in every past conversation by default.",
          isCap: true,
          why: "Cap. A model only sees what's in its context window right now. Some apps add memory features on top, but the model itself doesn't remember.",
        },
        {
          id: "tt-105",
          type: "choice",
          prompt: "You ask about yesterday's game and the AI has no idea. Most likely reason?",
          options: ["It's broken", "Its training data stops at a cutoff date", "It doesn't like sports"],
          answer: 1,
          why: "Models learn from data up to a cutoff. Newer events need search or tools to be looked up.",
        },
        {
          id: "tt-106",
          type: "order",
          prompt: "Put how a chatbot answers you in order:",
          steps: ["Your message is split into tokens", "The model reads all the tokens in its context", "It predicts the next token", "It adds that token and repeats", "The tokens become words on your screen"],
          why: "Split, read, predict, repeat. That loop is the whole trick, done very fast.",
        },
      ],
    },
    {
      id: "why-wrong",
      title: "Why it gets things wrong",
      blurb: "Prediction isn't the same as knowing.",
      cards: [
        {
          id: "tt-201",
          type: "choice",
          prompt: "Why can an AI make up a fake fact that sounds real?",
          options: ["It's lying on purpose", "It predicts likely-sounding text, and likely-sounding isn't always true", "It's hacked"],
          answer: 1,
          why: "The model optimises for text that fits, not for truth. That's where made-up answers come from.",
          meme: { kind: "expect", expectation: "AI looks up the answer", reality: "AI writes what an answer usually looks like" },
        },
        {
          id: "tt-202",
          type: "predict",
          context: "According to a famous study, people use only 10% of their ___",
          options: [{ token: "brain", p: 0.89 }, { token: "time", p: 0.05 }, { token: "phone", p: 0.01 }],
          why: "The model will happily finish a popular myth. The 10% brain thing is false, but it's a very common sentence.",
        },
        {
          id: "tt-203",
          type: "cap",
          claim: "AI models can count the letters in a word perfectly every time.",
          isCap: true,
          why: "Cap. Models see tokens, not letters, so counting letters (like the r's in strawberry) can trip them up.",
        },
        {
          id: "tt-204",
          type: "choice",
          prompt: "Best way to trust an AI's fact?",
          options: ["It said it confidently", "Check it against a reliable source", "Ask it if it's sure"],
          answer: 1,
          why: "Verify outside the chat. Asking \"are you sure?\" just gets another prediction.",
        },
        {
          id: "tt-205",
          type: "type",
          prompt: "When an AI confidently makes something up, it's called a ____________.",
          accept: ["hallucination", "hallucinations"],
          hint: "like seeing things that aren't there",
          why: "Hallucination: confident, fluent and wrong. Head to Cap Detector to hunt them.",
        },
      ],
    },
  ],
};
